/**
 * The canonical failure taxonomy. Rule packs and connectors classify every
 * failure into exactly one of these categories. Keep this list stable — report
 * consumers, SARIF rule ids, and Jira automation key off these strings.
 */
export const FAILURE_CATEGORIES = [
  'auth.authentication',
  'auth.authorization',
  'auth.secret_missing_or_expired',
  'network.connectivity',
  'network.rate_limit',
  'network.timeout',
  'fs.missing_file',
  'fs.incorrect_path',
  'schema.drift',
  'schema.missing_column',
  'schema.type_mismatch',
  'data.null_violation',
  'data.duplicate_records',
  'data.referential_integrity',
  'data.contract_violation',
  'data.unexpected_rowcount',
  'sql.syntax_or_compilation',
  'sql.missing_object',
  'code.python_exception',
  'compute.spark_failure',
  'deps.package_conflict',
  'deps.version_mismatch',
  'env.runtime_drift',
  'env.configuration_drift',
  'compute.out_of_memory',
  'compute.resource_limit',
  'param.incorrect',
  'deploy.failure',
  'infra.warehouse_or_cluster',
  'data.upstream_unavailable',
  'service.downstream_unavailable',
  'run.partial_execution',
  'perf.query_regression',
  'perf.missing_index',
  'governance.permission',
  'unknown',
] as const;

export type FailureCategory = (typeof FAILURE_CATEGORIES)[number];

/** Human-facing labels for reports. */
export const CATEGORY_LABELS: Record<FailureCategory, string> = {
  'auth.authentication': 'Authentication failure',
  'auth.authorization': 'Authorization failure',
  'auth.secret_missing_or_expired': 'Missing or expired secret',
  'network.connectivity': 'API / network connectivity',
  'network.rate_limit': 'Rate limit exceeded',
  'network.timeout': 'Timeout',
  'fs.missing_file': 'Missing file',
  'fs.incorrect_path': 'Incorrect path',
  'schema.drift': 'Schema drift',
  'schema.missing_column': 'Missing column',
  'schema.type_mismatch': 'Data-type mismatch',
  'data.null_violation': 'Null-value violation',
  'data.duplicate_records': 'Duplicate records',
  'data.referential_integrity': 'Referential-integrity failure',
  'data.contract_violation': 'Data-contract violation',
  'data.unexpected_rowcount': 'Unexpected row-count change',
  'sql.syntax_or_compilation': 'SQL syntax / compilation error',
  'sql.missing_object': 'Missing database object',
  'code.python_exception': 'Python exception',
  'compute.spark_failure': 'Spark failure',
  'deps.package_conflict': 'Package conflict',
  'deps.version_mismatch': 'Dependency-version difference',
  'env.runtime_drift': 'Runtime / environment drift',
  'env.configuration_drift': 'Configuration drift',
  'compute.out_of_memory': 'Out-of-memory failure',
  'compute.resource_limit': 'Compute resource limitation',
  'param.incorrect': 'Incorrect parameter',
  'deploy.failure': 'Deployment failure',
  'infra.warehouse_or_cluster': 'Warehouse / cluster failure',
  'data.upstream_unavailable': 'Upstream data unavailable',
  'service.downstream_unavailable': 'Downstream service unavailable',
  'run.partial_execution': 'Partial pipeline execution',
  'perf.query_regression': 'Query performance regression',
  'perf.missing_index': 'Missing index',
  'governance.permission': 'Permission / governance failure',
  unknown: 'Unclassified failure',
};
